theme: jekyll-theme-minimal

logo: 'IMG_20210318_222443_199.jpg'

title: 'Yorgos Psarellis'

description: 'Machine Learning Scientist           <br>                    PhD Candidate @ JHU'                         

